name: Run External CICD Script

on:
  workflow_dispatch:

jobs:
  run-cicd:
    runs-on: self-hosted   # ya ubuntu-latest / windows-latest as per environment

    steps:
      - name: Checkout CICD repo
        uses: actions/checkout@v3
        with:
          repository: sahlshah98922/common_workflow   # yeh tera CICD repo ka naam
          token: ${{ secrets.GH_PAT }}                # PAT with repo read access
          ref: main                                   # branch name

      - name: Run CICD script
        shell: pwsh
        run: common_workflow/CICD.yaml
