name: Trigger Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CICD.yaml
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            https://api.github.com/repos/sahlshah98922/CICD.yaml/dispatches \
            -d '{"ref":"main"}'
