name: Run External CICD Script

on:
  workflow_dispatch:

jobs:
  run-cicd:
    runs-on: ubuntu-latest

    steps:
      
      # Step 2: Checkout common_workflow repo jisme CICD.yaml hai
      - name: Checkout CICD repo
        uses: actions/checkout@v3
        with:
          repository: sahlshah98922/common_workflow   # <--- repo jisme CICD.yaml hai
          token: ${{ secrets.GH_PAT }}
          ref: main
          path: common_workflow  # is folder me checkout hoga

      # Step 3: Run the script instead of YAML
      - name: Run CICD script
        run: ./common_workflow/CICD.yaml

