name: Parameterized CI Pipeline

on:
  workflow_dispatch:
    inputs:
      env:
        description: Select Environment
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

env:
  IMAGE_NAME: onlinebookstore
  JFROG_REPO: docker-local

jobs:
  ci:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Verify Maven
        run: mvn -version

      - name: Maven Build
        run: mvn clean package

      - name: Sonar Scan + Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn sonar:sonar
          -Dsonar.projectKey=OnlineBookStore-${{ inputs.env }}
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
          -Dsonar.qualitygate.wait=true
