name: Parameterized CI Pipeline with Manual Approval

on:
  workflow_dispatch:
    inputs:
      env:
        description: Select Environment
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

env:
  IMAGE_NAME: onlinebookstore
  IMAGE_TAG: ${{ github.sha }}

# ============================
# CI + DOCKER BUILD & PUSH
# ============================
jobs:
  ci:
    name: Build, Scan & Docker Push
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Maven Build
        run: mvn clean package -DskipTests

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=OnlineBookStore-${{ inputs.env }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Docker Build
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:${{ inputs.env }}

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
             -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Push
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG \
            ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

          docker tag $IMAGE_NAME:${{ inputs.env }} \
            ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ inputs.env }}
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ inputs.env }}

# ============================
# MANUAL APPROVAL JOB
# ============================
  approval:
    name: Manual Approval2
    needs: ci
    runs-on: ubuntu-latest
    environment:
      name: manual-approval2
    steps:
      - name: Waiting for approval
        run: echo "Waiting for manual approval to continue deployment"

# ============================
# DEPLOY JOB (AFTER APPROVAL)
# ============================
  deploy:
    name: Deploy Application
    needs: approval
    runs-on: self-hosted
    steps:
      - name: Deploy Step
        run: echo "🚀 Deployment started after approval for ${{ inputs.env }}"
