name: Deploy to Kubeadm Cluster (Dockerized)

on:
  push:
    branches:
      - main 

jobs:
  # ================= CI JOB (Runs on Build Machine) =================
  build-and-push:
    runs-on: [self-hosted, Linux, X64]
    name: Code Build and Docker Push
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/onlinebookstore:latest .

    - name: Push Image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/onlinebookstore:latest

  # ================= CD JOB (Runs on Kubeadm Master Node) =================
  deploy-to-kubeadm:
    needs: build-and-push
    runs-on: [self-hosted, Linux, X64]
    name: Kubernetes Cluster Deployment
    steps:
    - name: Checkout Manifests
      uses: actions/checkout@v4

    - name: Apply Kubernetes Manifests
      run: |
        # Manifest apply karein
        kubectl apply -f deployment.yaml
        
        # Nayi image force pull karne ke liye rollout restart (Aapke deployment ke naam ke sath)
        kubectl rollout restart deployment/onlinebookstore
