name: Deploy to Kubeadm Cluster (Dockerized)

on:
  push:
    branches:
      - main 

jobs:
  # ================= CI JOB (Runs strictly on Build Runner) =================
  build-and-push:
    # Aapke naye runner ka exact naam explicitly target kiya hai
    runs-on: cd-runner-build
    name: Code Build and Docker Push
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/onlinebookstore:latest .

    - name: Push Image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/onlinebookstore:latest

  # ================= CD JOB (Runs strictly on Kubeadm Master Node) =================
  deploy-to-kubeadm:
    needs: build-and-push
    # Aapke purane master runner node ka exact naam target kiya hai
    runs-on: master
    name: Kubernetes Cluster Deployment
    steps:
    - name: Checkout Manifests
      uses: actions/checkout@v4

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f deployment.yaml
        kubectl rollout restart deployment/onlinebookstore

